---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep3
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sampleweb
  template:
    metadata:
      labels:
        run: sampleweb
    spec:
      containers:
      - name: sampleweb
        image: gcr.io/mystic-impulse-245222/sample

---

apiVersion: v1
kind: Service
metadata:
  name: myservice3
  labels:
    run: sampleweb
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: sampleweb
  type: LoadBalancer
