---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep3
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: gcr.io/mystic-impulse-245222/image3
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: myservice3
  labels:
    run: tomcat
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: tomcat
  type: LoadBalancer


